// Study Soundtrack — the study-mode vibe player.
//
// A compact, beautiful one-tap music surface for Study Mode, wired to the
// app-root MusicProvider (the same synthesized engine that powers the
// Focus page: zero audio files, zero autoplay on first visit, everything
// generated by the Web Audio API).
//
// Why it exists: the reader's Study Mode strips every distraction EXCEPT
// the one thing that helps — a calm soundtrack. The classical pieces
// (Bach / Mozart / Beethoven / Pachelbel) are public-domain compositions
// synthesized live from MIDI note data, so they stream from nowhere, load
// instantly, and never touch our servers.
//
// Design: collapsed glass pill with a live equalizer; expands into a
// curated panel — Classical first, study-friendly ambience below — with
// volume. Play state survives exiting Study Mode (provider lives at the
// app root), so a student can hop between Focus and the reader.

import { useState } from "react";
import { motion } from "framer-motion";
import { ChevronDown, Music2, Pause, Play, Volume2 } from "lucide-react";
import { useMusic } from "@/components/music-player";
import { cn } from "@/lib/utils";

// Curated for reading/study — Classical headline acts + calm beds.
const CLASSICAL_PICKS = [
  { id: "bach_prelude_c", label: "Bach", hint: "Prelude in C · BWV 846" },
  { id: "pachelbel_canon", label: "Pachelbel", hint: "Canon in D" },
  { id: "mozart_eine_kleine", label: "Mozart", hint: "Romanza" },
  { id: "beethoven_ode", label: "Beethoven", hint: "Ode to Joy" },
] as const;

const AMBIENCE_PICKS = [
  { id: "rain", label: "Rain", hint: "soft rain on a tin roof" },
  { id: "brown", label: "Brown noise", hint: "deep, low distraction" },
  { id: "cafe", label: "Café", hint: "soft coffee-shop murmur" },
  { id: "singing_bowl", label: "Singing bowl", hint: "resonant tone" },
] as const;

export function StudySoundtrack() {
  const [open, setOpen] = useState(false);
  const {
    playing,
    track,
    toggle,
    selectTrack,
    volume,
    setVolume,
  } = useMusic();

  const isPlaying = playing;

  return (
    <motion.div
      initial={{ opacity: 0, y: -12, scale: 0.96 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ delay: 0.16, type: "spring", stiffness: 320, damping: 30 }}
      className="pointer-events-none absolute right-3 top-16 z-40 flex flex-col items-end sm:right-5 sm:top-[4.25rem]"
    >
      {/* ── Expanded panel ── */}
      {open && (
        <motion.div
          initial={{ opacity: 0, y: -8, scale: 0.97 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          transition={{ duration: 0.18, ease: [0.22, 1, 0.36, 1] }}
          className="pointer-events-auto mb-2 w-[264px] overflow-hidden rounded-2xl border border-foreground/10 bg-background/95 shadow-[0_20px_60px_-16px_rgba(0,0,0,0.55)] backdrop-blur-2xl"
        >
          <div className="relative border-b border-foreground/[0.06] px-4 pb-2.5 pt-3">
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-amber-300/50 to-transparent" />
            <p className="type-mono text-[9px] font-bold uppercase tracking-[0.22em] text-amber-700 dark:text-amber-300">
              Study soundtrack
            </p>
            <p className="type-caption mt-0.5 text-[10px] leading-snug text-muted-foreground/60">
              Synthesized live — no downloads, works offline.
            </p>
          </div>

          <div className="px-2.5 py-2.5">
            <p className="type-mono mb-1.5 px-1 text-[8.5px] uppercase tracking-[0.2em] text-muted-foreground/40">
              Classical
            </p>
            <div className="grid grid-cols-2 gap-1.5">
              {CLASSICAL_PICKS.map((pick) => {
                const active = track.id === pick.id;
                return (
                  <button
                    key={pick.id}
                    type="button"
                    onClick={() => selectTrack(pick.id)}
                    title={pick.hint}
                    className={cn(
                      "group flex cursor-pointer flex-col rounded-xl border px-2.5 py-2 text-left transition-all active:scale-[0.97]",
                      active
                        ? "border-amber-400/40 bg-amber-400/[0.12] dark:bg-amber-300/[0.1]"
                        : "border-foreground/[0.07] bg-foreground/[0.02] hover:border-amber-400/25 hover:bg-amber-400/[0.06]",
                    )}
                  >
                    <span
                      className={cn(
                        "type-caption text-[11px] font-semibold leading-tight",
                        active ? "text-amber-700 dark:text-amber-200" : "text-foreground/80",
                      )}
                    >
                      {pick.label}
                    </span>
                    <span className="type-mono mt-0.5 truncate text-[8px] uppercase tracking-wider text-muted-foreground/45">
                      {pick.hint}
                    </span>
                  </button>
                );
              })}
            </div>

            <p className="type-mono mb-1.5 mt-3 px-1 text-[8.5px] uppercase tracking-[0.2em] text-muted-foreground/40">
              Ambience
            </p>
            <div className="grid grid-cols-2 gap-1.5">
              {AMBIENCE_PICKS.map((pick) => {
                const active = track.id === pick.id;
                return (
                  <button
                    key={pick.id}
                    type="button"
                    onClick={() => selectTrack(pick.id)}
                    title={pick.hint}
                    className={cn(
                      "group flex cursor-pointer items-center rounded-xl border px-2.5 py-2 text-left transition-all active:scale-[0.97]",
                      active
                        ? "border-primary/40 bg-primary/[0.1]"
                        : "border-foreground/[0.07] bg-foreground/[0.02] hover:border-primary/25 hover:bg-primary/[0.05]",
                    )}
                  >
                    <span
                      className={cn(
                        "type-caption truncate text-[11px] font-semibold",
                        active ? "text-primary" : "text-foreground/80",
                      )}
                    >
                      {pick.label}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Volume */}
            <div className="mt-3 flex items-center gap-2 rounded-xl border border-foreground/[0.06] bg-foreground/[0.02] px-3 py-2">
              <Volume2 className="size-3.5 shrink-0 text-muted-foreground/60" />
              <input
                type="range"
                min={0}
                max={1}
                step={0.01}
                value={volume}
                onChange={(e) => setVolume(Number(e.target.value))}
                aria-label="Soundtrack volume"
                className="h-1 w-full cursor-pointer accent-amber-400"
              />
              <span className="type-mono w-7 shrink-0 text-right text-[9px] tabular-nums text-muted-foreground/50">
                {Math.round(volume * 100)}
              </span>
            </div>
          </div>
        </motion.div>
      )}

      {/* ── Collapsed pill ── */}
      <button
        type="button"
        onClick={() => {
          if (!open && !playing) {
            // One tap from nothing to Bach — the instant-study moment.
            selectTrack("bach_prelude_c");
            if (!playing) toggle();
            setOpen(true);
            return;
          }
          setOpen((v) => !v);
        }}
        className={cn(
          "pointer-events-auto flex cursor-pointer items-center gap-2 rounded-full border py-1.5 pl-3 pr-2.5 shadow-[0_12px_40px_-8px_rgba(0,0,0,0.5)] backdrop-blur-2xl transition-all active:scale-[0.97]",
          playing
            ? "border-amber-400/35 bg-background/90 dark:bg-black/70"
            : "border-amber-400/25 bg-background/85 dark:bg-black/60 hover:border-amber-400/45",
        )}
        aria-label={open ? "Close study soundtrack" : "Open study soundtrack"}
        title={playing ? `Now playing — ${track.label}` : "Study soundtrack"}
      >
        {/* Live equalizer when playing, static note when idle */}
        {playing ? (
          <span className="flex h-3.5 items-end gap-[2.5px]" aria-hidden="true">
            {[0, 1, 2, 3].map((i) => (
              <span
                key={i}
                className="w-[2.5px] origin-bottom rounded-full bg-amber-500 dark:bg-amber-300"
                style={{
                  height: "100%",
                  animation: `eq-bar ${0.7 + i * 0.13}s ease-in-out ${i * 0.11}s infinite`,
                }}
              />
            ))}
          </span>
        ) : (
          <Music2 className="size-3.5 text-amber-600 dark:text-amber-300" />
        )}
        <span className="type-caption max-w-[128px] truncate text-[11px] font-semibold text-amber-700 dark:text-amber-200">
          {isPlaying ? track.label : "Study soundtrack"}
        </span>
        {playing ? (
          <span
            role="button"
            tabIndex={0}
            onClick={(e) => {
              e.stopPropagation();
              toggle();
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.stopPropagation();
                toggle();
              }
            }}
            className="flex size-6 cursor-pointer items-center justify-center rounded-full border border-amber-400/25 bg-amber-400/10 text-amber-700 transition-all hover:bg-amber-400/20 dark:text-amber-200"
            aria-label={playing ? "Pause soundtrack" : "Play soundtrack"}
          >
            {playing ? <Pause className="size-3" /> : <Play className="size-3" />}
          </span>
        ) : (
          <Play className="size-3 text-amber-600 dark:text-amber-300" />
        )}
        <ChevronDown
          className={cn(
            "size-3 text-muted-foreground/50 transition-transform duration-200",
            open && "rotate-180",
          )}
        />
      </button>
    </motion.div>
  );
}
