// Daily motivation engine.
//
// One quote per calendar day, deterministic so every student sees the same
// quote that day. The quote is normally generated by Groq on a daily
// cron; getTodaysQuote falls back to a hand-written pool (deterministic by
// day-of-year) so users are never left with nothing on a cold start or while
// the API key is missing.

import { v } from "convex/values";
import {
  action,
  internalAction,
  internalMutation,
  internalQuery,
  query,
} from "./_generated/server";
import { internal } from "./_generated/api";
import { callGemini, resolveKey } from "./gemini";

// Original fallback pool, written for this product. Used deterministically by
// day-of-year so all users share the same quote on the same day.
const FALLBACK_QUOTES: { text: string; author?: string }[] = [
  { text: "The exam is a marathon of four years. Start today, not in May.", author: "Nexus Academy" },
  { text: "Past papers are the closest thing to a rehearsal. Treat every one like the real stage.", author: "Nexus Academy" },
  { text: "One topic a day beats panic in a week. Small, steady, relentless.", author: "Nexus Academy" },
  { text: "You don't need to be brilliant — you need to be consistent.", author: "Nexus Academy" },
  { text: "Every hour you study now is a mark you keep on exam day.", author: "Nexus Academy" },
  { text: "Hard topics aren't walls. They're just stairs you haven't climbed yet.", author: "Nexus Academy" },
  { text: "Your competition isn't other students. It's the version of you that gave up early.", author: "Nexus Academy" },
  { text: "Revise like you already failed once and refuse to do it again.", author: "Nexus Academy" },
  { text: "Focus is a skill, and you just trained it again today.", author: "Nexus Academy" },
  { text: "Nobody remembers the days you almost studied. They remember the days you did.", author: "Nexus Academy" },
  { text: "The syllabus is long. The exam is one morning. Plan backwards from it.", author: "Nexus Academy" },
  { text: "Mistakes in practice are tuition. Mistakes on exam day are expensive.", author: "Nexus Academy" },
  { text: "Rest is part of the plan. Even engines cool down.", author: "Nexus Academy" },
  { text: "Ask the tutor the question you're embarrassed to ask. That's how you learn.", author: "Nexus Academy" },
  { text: "Four years of material. One day at a time. You've already started.", author: "Nexus Academy" },
];

function todayKey(): string {
  return new Date().toISOString().slice(0, 10);
}

function dayOfYear(dateKey: string): number {
  const [y, m, d] = dateKey.split("-").map(Number);
  const start = Date.UTC(y!, 0, 0);
  const day = Date.UTC(y!, m! - 1, d!);
  return Math.floor((day - start) / 86_400_000);
}

function fallbackForDate(dateKey: string): { text: string; author?: string } {
  return FALLBACK_QUOTES[dayOfYear(dateKey) % FALLBACK_QUOTES.length]!;
}

async function requestQuoteFromAI(ctx: any): Promise<{ text: string; author?: string }> {
  const text = await callGemini(ctx, {
    systemPrompt:
      "You write one short motivational quote for an Ethiopian student grinding " +
      "through national exam prep (grades 9-12, ESLCE). Tone: sincere, precise, a " +
      "little gritty — never corporate-poster cheesy, no hashtags, no clichés about " +
      "dreams or hustling. One or two sentences, under 140 characters. " +
      "Respond with the quote text only — no quotation marks, no attribution.",
    userMessage: "Write today's quote for a student who opened their study app.",
    maxTokens: 120,
    temperature: 0.9,
  });
  return { text: text.replace(/^["']|["']$/g, "").trim() };
}

// ---------------------------------------------------------------------------
// Internal plumbing
// ---------------------------------------------------------------------------

export const getQuoteByDate = internalQuery({
  args: { date: v.string() },
  handler: async (ctx, { date }) =>
    (await ctx.db
      .query("dailyQuotes")
      .withIndex("by_date", (q) => q.eq("dateAssigned", date))
      .unique()) ?? null,
});

export const insertQuote = internalMutation({
  args: {
    text: v.string(),
    author: v.optional(v.string()),
    dateAssigned: v.string(),
  },
  handler: async (ctx, args) => await ctx.db.insert("dailyQuotes", args),
});

export const generateTodaysQuoteAction = internalAction({
  args: {},
  handler: async (ctx) => {
    const date = todayKey();
    const existing = await ctx.runQuery(internal.quotes.getQuoteByDate, { date });
    if (existing) return { ok: true, reused: true };

    let quote: { text: string; author?: string };
    const hasKey = await resolveKey(ctx, "GROQ_API_KEY");
    if (hasKey || process.env.GROQ_API_KEY) {
      try {
        quote = await requestQuoteFromAI(ctx);
      } catch {
        quote = fallbackForDate(date);
      }
    } else {
      quote = fallbackForDate(date);
    }

    await ctx.runMutation(internal.quotes.insertQuote, {
      text: quote.text,
      author: quote.author,
      dateAssigned: date,
    });
    return { ok: true, reused: false };
  },
});

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export const getTodaysQuote = query({
  args: {},
  handler: async (ctx) => {
    const date = todayKey();
    const row = await ctx.db
      .query("dailyQuotes")
      .withIndex("by_date", (q) => q.eq("dateAssigned", date))
      .unique();
    if (row) {
      return {
        text: row.text,
        author: row.author ?? null,
        dateAssigned: row.dateAssigned,
        generated: true,
      };
    }
    const fallback = fallbackForDate(date);
    return {
      text: fallback.text,
      author: fallback.author ?? null,
      dateAssigned: date,
      generated: false,
    };
  },
});

export const ensureTodaysQuote = action({
  args: {},
  handler: async (ctx) => {
    await ctx.runAction(internal.quotes.generateTodaysQuoteAction, {});
    return { ok: true };
  },
});
